services:
  - type: web
    name: jumper-music-eval
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    disks:
      - name: data
        mountPath: /opt/render/project/src
        sizeGB: 1
