services:
  - type: web
    name: jumper-music-eval
    env: python
    region: frankfurt  # oder oregon, je nachdem wo du bist
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true

    # Falls du eine SQLite-DB (z. B. data.db) hast â€“ das macht sie persistent!
    disks:
      - name: data
        mountPath: /opt/render/project/src
        sizeGB: 1
